// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rh.Infrastructure.Data;

#nullable disable

namespace rh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217081305_UpdateAnnonceRelations")]
    partial class UpdateAnnonceRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rh.Domain.Entities.Annonce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetenceRequis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdModeTravail")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeContrat")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModeTravailId")
                        .HasColumnType("int");

                    b.Property<string>("NiveauExperience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeContratId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModeTravailId");

                    b.HasIndex("TypeContratId");

                    b.ToTable("Annonces");
                });

            modelBuilder.Entity("rh.Domain.Entities.ModeTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModeTravails");
                });

            modelBuilder.Entity("rh.Domain.Entities.TypeContrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeContrats");
                });

            modelBuilder.Entity("rh.Domain.Entities.Annonce", b =>
                {
                    b.HasOne("rh.Domain.Entities.ModeTravail", "ModeTravail")
                        .WithMany("Annonces")
                        .HasForeignKey("ModeTravailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rh.Domain.Entities.TypeContrat", "TypeContrat")
                        .WithMany("Annonces")
                        .HasForeignKey("TypeContratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeTravail");

                    b.Navigation("TypeContrat");
                });

            modelBuilder.Entity("rh.Domain.Entities.ModeTravail", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("rh.Domain.Entities.TypeContrat", b =>
                {
                    b.Navigation("Annonces");
                });
#pragma warning restore 612, 618
        }
    }
}
