// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rh.Infrastructure.Data;

#nullable disable

namespace rh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217080236_CreateModeTravail")]
    partial class CreateModeTravail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rh.Domain.Entities.Annonce", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("ModeTravailId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeContratId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ModeTravailId");

                    b.HasIndex("TypeContratId");

                    b.ToTable("Annonces");
                });

            modelBuilder.Entity("rh.Domain.Entities.ModeTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModeTravails");
                });

            modelBuilder.Entity("rh.Domain.Entities.TypeContrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeContrats");
                });

            modelBuilder.Entity("rh.Domain.Entities.Annonce", b =>
                {
                    b.HasOne("rh.Domain.Entities.ModeTravail", null)
                        .WithMany("Annonces")
                        .HasForeignKey("ModeTravailId");

                    b.HasOne("rh.Domain.Entities.TypeContrat", null)
                        .WithMany("Annonces")
                        .HasForeignKey("TypeContratId");
                });

            modelBuilder.Entity("rh.Domain.Entities.ModeTravail", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("rh.Domain.Entities.TypeContrat", b =>
                {
                    b.Navigation("Annonces");
                });
#pragma warning restore 612, 618
        }
    }
}
