// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rh.Infrastructure.Data;

#nullable disable

namespace rh.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219054953_InitCandidatures")]
    partial class InitCandidatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rh.Domain.Entities.Annonce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompetenceRequis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<int>("IdModeTravail")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeContrat")
                        .HasColumnType("int");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbDossierValide")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NiveauExperience")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdModeTravail");

                    b.HasIndex("IdTypeContrat");

                    b.ToTable("Annonces");
                });

            modelBuilder.Entity("rh.Domain.Entities.Candidat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PieceJointe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Candidat");
                });

            modelBuilder.Entity("rh.Domain.Entities.Candidature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("IdAnnonce")
                        .HasColumnType("int");

                    b.Property<long>("IdCandidat")
                        .HasColumnType("bigint");

                    b.Property<long>("IdStatut")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdAnnonce");

                    b.HasIndex("IdCandidat");

                    b.HasIndex("IdStatut");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("rh.Domain.Entities.ModeTravail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModeTravails");
                });

            modelBuilder.Entity("rh.Domain.Entities.Statut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statut");
                });

            modelBuilder.Entity("rh.Domain.Entities.TypeContrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeContrats");
                });

            modelBuilder.Entity("rh.Domain.Entities.Annonce", b =>
                {
                    b.HasOne("rh.Domain.Entities.ModeTravail", "ModeTravail")
                        .WithMany("Annonces")
                        .HasForeignKey("IdModeTravail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rh.Domain.Entities.TypeContrat", "TypeContrat")
                        .WithMany("Annonces")
                        .HasForeignKey("IdTypeContrat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeTravail");

                    b.Navigation("TypeContrat");
                });

            modelBuilder.Entity("rh.Domain.Entities.Candidature", b =>
                {
                    b.HasOne("rh.Domain.Entities.Annonce", "Annonce")
                        .WithMany("Candidatures")
                        .HasForeignKey("IdAnnonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rh.Domain.Entities.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("IdCandidat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rh.Domain.Entities.Statut", "Statut")
                        .WithMany("Candidatures")
                        .HasForeignKey("IdStatut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonce");

                    b.Navigation("Candidat");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("rh.Domain.Entities.Annonce", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("rh.Domain.Entities.Candidat", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("rh.Domain.Entities.ModeTravail", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("rh.Domain.Entities.Statut", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("rh.Domain.Entities.TypeContrat", b =>
                {
                    b.Navigation("Annonces");
                });
#pragma warning restore 612, 618
        }
    }
}
